name: .NET Core

on:
  push:
    branches: [ Perf ]
  pull_request:
    branches: [ Perf ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
         persist-credentials: false
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish --configuration Release --no-restore "/home/runner/work/BlazorTourOfHeroes/BlazorTourOfHeroes/TourofHeroes/TourofHeroes.csproj"
    - name: Publish to GitHub Pages
      run: |
          mkdir /home/runner/work/BlazorTourOfHeroes/BlazorTourOfHeroes/TourofHeroes/bin/Release/netstandard2.1/topublish
          cd /home/runner/work/BlazorTourOfHeroes/BlazorTourOfHeroes/TourofHeroes/bin/Release/netstandard2.1/topublish
          git init
          git remote add origin https://$REPO_KEY@github.com/gopkumr/BlazorHost.git
          git checkout -b master
          git config user.name ${GITHUB_ACTOR}
          git config user.email ${GITHUB_ACTOR}@user.github.com
          git fetch --prune
          git rm -r --ignore-unmatch '*'
          cp -avr /home/runner/work/BlazorTourOfHeroes/BlazorTourOfHeroes/TourofHeroes/bin/Release/netstandard2.1/wwwroot /home/runner/work/BlazorTourOfHeroes/BlazorTourOfHeroes/TourofHeroes/bin/Release/netstandard2.1/topublish
          git add --all
          git commit -m 'Adding new set of file'
          git push origin
      env:
        REPO_KEY: ${{ secrets.ACCESS_TOKEN }}
